### ISSUE TITLE
Add support for VPN HA

### ISSUE THREAD

**Issue by ocervell** [terraform-google-modules/terraform-google-vpn#27]
There is a new resource allowing to have HA for VPN tunnels: https://www.terraform.io/docs/providers/google/r/compute_ha_vpn_gateway.html

Let's add support for it !

**Comment by averbuks** [comment]
Hi @ocervell, @morgante, I think it's better to have vpn-ha as a separate module (submodule), it's using different kind of gateway and set of parameters, in case of adjusting it to existing module it will add a lot of complexity. Also I think we may split existing module to dynamic + static submodules and get rid of the main module. WDYT?

**Comment by morgante** [comment]
> Hi @ocervell, @morgante, I think it's better to have vpn-ha as a separate module (submodule), it's using different kind of gateway and set of parameters, in case of adjusting it to existing module it will add a lot of complexity. 

I think that's a good idea, agreed.

> Also I think we may split existing module to dynamic + static submodules and get rid of the main module.

Agreed.
