### ISSUE TITLE
cr_enabled attribute is missing from terraform registry inputs

### ISSUE THREAD

**Issue by alekhyal** [terraform-google-modules/terraform-google-vpn#29]
Not able to use terraform registry link as "source" and enable ``` cr_enabled=true ``` as it is not part of Inputs. Because of this ```cr_enabled = false``` (default) at all times.
Terraform registry link - https://registry.terraform.io/modules/terraform-google-modules/vpn/google/0.2.0?tab=inputs

**Comment by morgante** [comment]
0.2.0 is a very old version, please use the latest 1.2.0 version we just released: https://registry.terraform.io/modules/terraform-google-modules/vpn/google/1.2.0

**Comment by alekhyal** [comment]
Thank you
