### ISSUE TITLE
CIDR Ranges in readme are invalid

### ISSUE THREAD

**Issue by rbrondgeest** [terraform-google-modules/terraform-google-vpn#30]
CIDR Ranges used in the snippets in the readme are not valid and, I would ecxpect they'd cause issues.

`bgp_cr_session_range     = ["169.254.0.1/30", "169.254.0.3/30"]`

169.254.0.1/30 is interpreted as 169.254.0.0/30 wich includes IP's 169.254.0.0 upto and including 169.254.0.3
169.254.0.3/30 is also interpreted as 169.254.0.0/30 wich also includes IP's 169.254.0.0  upto and including 169.254.0.3

The example would be valid in this scenario, perhaps to prevent confusion you might want to fix this in the readme?
`bgp_cr_session_range     = ["169.254.0.0/30", "169.254.0.4/30"]`

**Comment by aaron-lane** [comment]
Thanks @rbrondgeest. Feel free to open a pull request!
