### ISSUE TITLE
Incorrect example for vpn_ha GCP to on-prem in README.md

### ISSUE THREAD

**Issue by abaumhauer** [terraform-google-modules/terraform-google-vpn#45]
The example in the README.md of https://github.com/terraform-google-modules/terraform-google-vpn/blob/master/modules/vpn_ha/README.md has the addresses swapped. The bgp_peer.address should be "169.254.1.2" and the bgp_session_range should be "169.254.1.1/30". As shown an error is thrown during TF apply that looks like the following:
```
Error: Error patching router us-east4/vpn-test: googleapi: Error 400: Invalid value for field 'resource.bgpPeers[1].ipAddress': ''. BGP Peer "vpn-test-remote-1" has IP address 169.254.1.2 different from interface IP address 169.254.1.3, invalid
```

**Comment by mananbolia66** [comment]
> The example in the README.md of https://github.com/terraform-google-modules/terraform-google-vpn/blob/master/modules/vpn_ha/README.md has the addresses swapped. The bgp_peer.address should be "169.254.1.2" and the bgp_session_range should be "169.254.1.1/30". As shown an error is thrown during TF apply that looks like the following:
> 
> ```
> Error: Error patching router us-east4/vpn-test: googleapi: Error 400: Invalid value for field 'resource.bgpPeers[1].ipAddress': ''. BGP Peer "vpn-test-remote-1" has IP address 169.254.1.2 different from interface IP address 169.254.1.3, invalid
> ```

Were you able to resolve this?
