### ISSUE TITLE
BGP session name already in use when creating single tunnels on two or more gateways

### ISSUE THREAD

**Issue by zolech** [terraform-google-modules/terraform-google-vpn#54]
I have <ins>3 vpn gateways (3 external IPs)</ins> and trying to use this module for creating <ins>single vpn tunnel for each of them</ins>. According to source code this module is trying to set the same BGP session name **bgp-session-0** for every tunnel because there is only one tunnel per IP. First tunnel is being created with no problems but the second and the third fails because session name should be unique. This code below works only if you create one or more tunnels on the same gateway:

`name                      = "bgp-session-${count.index}"`

Session name should be more complex to avoid failing in this scenario, for example:
`name                      = "bgp-session-${local.tunnel_name_prefix}-${count.index}"`

**Comment by zolech** [comment]
@morgante any comment on this ?

**Comment by morgante** [comment]
@zolech Can you point where in the code that name is being used? I can't find `bgp-session` in our codebase.

**Comment by morgante** [comment]
Thanks, yes it looks like we probably need to incorporate tunnel_name_pefix into the name. I'm happy to review a PR.
