### ISSUE TITLE
Add variable `route_tags` to route definition with instance tags to which this route applies

### ISSUE THREAD

**Issue by damianjaniszewski** [terraform-google-modules/terraform-google-vpn#56]
Feature request:
Add `route_tags` (optional) variable in the module so defined routes will have instance tag specified.
Variable should be passed as `tags` to resource `"google_compute_route" "route"` in `main.tf`.

Example variable def:
```
variable "route_tags" {
  type    = list(string)
  description = "A list of instance tags to which this route applies."
  default = []
}
```

**Comment by morgante** [comment]
This sounds like a reasonable addition and we will add it to the backlog. If you'd like it added sooner, we're also happy to review a pull request.
